### ISSUE TITLE
Use OSSM v2.6 instead of Istio in nightly pipelines

### ISSUE THREAD

**Issue by trepel** [Kuadrant/testsuite-pipelines#35]
**Summary**

Use OSSM (Openshift Service Mesh) v2.6 instead of Istio as a GatewayAPI implementation in nightly pipelines.

Not actionable untit the support for it is implemented, tracked in https://issues.redhat.com/browse/CONNLINK-230

First step would be to basically follow https://github.com/Kuadrant/testsuite/wiki/Guide-to-prepare-Openshift-cluster-to-run-testsuite with the Istio/Sail related pieces replaced with OSSM specific stuff:

Install OSSM Operator via OLM:
```
oc create -n openshift-operators -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: servicemeshoperator.v2.6.0
EOF
```

Create SMCP CR:
```
oc create -n istio-system -f - <<EOF
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: istiocontrolplane
spec:
  version: v2.6
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  addons:
    prometheus:
      enabled: false
    kiali:
      enabled: false
    grafana:
      enabled: false
EOF
```

Wait for OSSM to get ready:
```
oc wait -n "istio-system" servicemeshcontrolplane/istiocontrolplane --for=condition=Ready=True
```

After that the guide should work as described, maybe with the exception of "Enable tracing for Istio" section.

If all good and testsuite passes successfully against the cluster discuss whether we want this to use in nightly pipelines or whether there are other options how to test this frequently. RHCL will use OSSM, not Istio so we need to have this covered somehow.
